#!/usr/bin/env node

/**
 * ContentForge AI - One-Click Setup Script
 * 
 * This script helps you set up your ContentForge AI instance.
 * Run: node scripts/setup.js
 */

const fs = require('fs');
const readline = require('readline');
const { execSync } = require('child_process');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (prompt) => new Promise((resolve) => rl.question(prompt, resolve));

console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║   ██████╗ ██████╗ ███╗   ██╗████████╗███████╗███╗   ██╗████████╗  ║
║  ██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝██╔════╝████╗  ██║╚══██╔══╝  ║
║  ██║     ██║   ██║██╔██╗ ██║   ██║   █████╗  ██╔██╗ ██║   ██║     ║
║  ██║     ██║   ██║██║╚██╗██║   ██║   ██╔══╝  ██║╚██╗██║   ██║     ║
║  ╚██████╗╚██████╔╝██║ ╚████║   ██║   ███████╗██║ ╚████║   ██║     ║
║   ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚══════╝╚═╝  ╚═══╝   ╚═╝     ║
║                                                               ║
║            ███████╗ ██████╗ ██████╗  ██████╗ ███████╗         ║
║            ██╔════╝██╔═══██╗██╔══██╗██╔════╝ ██╔════╝         ║
║            █████╗  ██║   ██║██████╔╝██║  ███╗█████╗           ║
║            ██╔══╝  ██║   ██║██╔══██╗██║   ██║██╔══╝           ║
║            ██║     ╚██████╔╝██║  ██║╚██████╔╝███████╗         ║
║            ╚═╝      ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝         ║
║                                                               ║
║                    AI Content Agency Setup                    ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
`);

async function setup() {
  console.log('Welcome! This script will help you set up your automated AI content agency.');
  console.log('You\'ll need accounts with: Stripe, Anthropic (Claude), and Resend.\n');

  const proceed = await question('Ready to begin? (y/n): ');
  if (proceed.toLowerCase() !== 'y') {
    console.log('Setup cancelled. Run this script again when ready!');
    rl.close();
    return;
  }

  console.log('\n📋 STEP 1: Gathering API Keys\n');
  console.log('You\'ll need to get API keys from three services:');
  console.log('1. Stripe: https://dashboard.stripe.com/apikeys');
  console.log('2. Anthropic: https://console.anthropic.com/account/keys');
  console.log('3. Resend: https://resend.com/api-keys\n');

  const stripeSecret = await question('Enter your Stripe Secret Key (sk_test_... or sk_live_...): ');
  const stripePublishable = await question('Enter your Stripe Publishable Key (pk_test_... or pk_live_...): ');
  const anthropicKey = await question('Enter your Anthropic API Key (sk-ant-...): ');
  const resendKey = await question('Enter your Resend API Key (re_...): ');
  const fromEmail = await question('Enter your FROM email address (e.g., orders@yourdomain.com): ');
  const siteUrl = await question('Enter your site URL (e.g., https://contentforge.ai): ');

  // Create .env.local file
  const envContent = `# ContentForge AI Configuration
# Generated by setup script on ${new Date().toISOString()}

# Stripe
STRIPE_SECRET_KEY=${stripeSecret}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${stripePublishable}
STRIPE_WEBHOOK_SECRET=whsec_placeholder

# Anthropic
ANTHROPIC_API_KEY=${anthropicKey}

# Resend
RESEND_API_KEY=${resendKey}
FROM_EMAIL=${fromEmail}

# Site
NEXT_PUBLIC_SITE_URL=${siteUrl.replace(/\/$/, '')}
`;

  fs.writeFileSync('.env.local', envContent);
  console.log('\n✅ Created .env.local file');

  console.log('\n📋 STEP 2: Installing Dependencies\n');
  console.log('Installing npm packages...');
  
  try {
    execSync('npm install', { stdio: 'inherit' });
    console.log('✅ Dependencies installed');
  } catch (error) {
    console.error('❌ Failed to install dependencies. Please run "npm install" manually.');
  }

  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║                      🎉 SETUP COMPLETE! 🎉                    ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝

📋 NEXT STEPS:

1. SET UP STRIPE WEBHOOK
   - Go to: https://dashboard.stripe.com/webhooks
   - Click "Add endpoint"
   - Enter URL: ${siteUrl}/api/webhook
   - Select event: "checkout.session.completed"
   - Copy the webhook signing secret
   - Update STRIPE_WEBHOOK_SECRET in .env.local

2. VERIFY YOUR RESEND DOMAIN
   - Go to: https://resend.com/domains
   - Add and verify your domain for email sending

3. TEST LOCALLY
   - Run: npm run dev
   - Visit: http://localhost:3000

4. DEPLOY TO PRODUCTION
   
   Option A: Vercel (Recommended - Free tier available)
   ─────────────────────────────────────────────────────
   a) Install Vercel CLI: npm install -g vercel
   b) Run: vercel
   c) Add environment variables in Vercel dashboard
   d) Update webhook URL in Stripe to your Vercel URL

   Option B: Any Node.js host (Railway, Render, etc.)
   ─────────────────────────────────────────────────────
   a) Push code to GitHub
   b) Connect repository to host
   c) Add environment variables
   d) Deploy and update webhook URL

💰 REVENUE PROJECTION:
   
   To reach $3,000/month:
   - Blog Basic ($49): 62 orders/month (~2/day)
   - Blog Premium ($99): 31 orders/month (~1/day)
   - Social Pack ($79): 38 orders/month (~1.3/day)
   - Content Bundle ($399): 8 orders/month (~2/week)

   Mix of services: ~40-60 orders/month average

📈 MARKETING TIPS:

   1. SEO: Your site is SEO-optimized. Content marketing works!
   2. Social proof: Ask happy customers for testimonials
   3. LinkedIn: Share content samples and case studies
   4. Partnerships: Reach out to marketing agencies
   5. Content marketing: Use your own service to blog!

Need help? The code is fully documented.
Good luck with your AI content agency! 🚀
`);

  rl.close();
}

setup().catch(console.error);
